### ISSUE TITLE
FREECODECAMP | Learn HTML by Building a Cat Photo App

### ISSUE THREAD

**Issue by nhanntcaodaion** [caodaion/caodaion.github.io#100]

**Comment by Sachin0611** [comment]
Hi! I am beginner in open source. Would like to contribute. Please guide.

**Comment by hiepntcaodaion** [comment]
![Image](https://github.com/caodaion/caodaion.github.io/assets/143392222/49cf0834-44d2-47b5-a441-3f2acaf0fc26)
Look good
