### ISSUE TITLE
DOCUMENTATION | PROJECT DOCUMENTATION | Statement of Work (SOW)

### ISSUE THREAD

**Issue by nhanntcaodaion** [caodaion/caodaion.github.io#41]
> Generally required if you are acting as a vendor in a project

 
Assuming that you are doing a project as an implementation service provider or outsourcing vendor, this is perhaps the most important document that is created in the pre-project phase.

In most companies, the sales/pre-sales/marketing department prepares the SOW, and this creates an issue down the line, as in most cases the project manager is unaware of the agreements that were made between the client and the vendor before the project.

A SOW is a technical document apart from the commercials. Therefore it makes sense to get it prepared by a Project Manager or someone with project management experience.

### WHAT IS AN SOW?
In most cases, a client and a vendor sign up on a legal master services agreement (MSA) for a fixed time. This MSA usually covers multiple projects. A SOW on the other hand is an agreement **covering a particular project**  — so if you have ten projects running with a vendor, you will have ten SOWs.

**What does an SOW contain?**

Typically, a well-written SOW will contain the following:

- Scope
- Assumptions
- Technology platform/Architecture
- Roles and Responsibilities of the client and the vendor
- Project Methodology
- A draft project times schedule with milestones
- Dependencies/Risks
- Acceptance Criteria
- Change Management Process

Sometimes, I have heard many people say, that before the project, how can I identify all dependencies and risks, and that is a fair question. The answer is that you do not have to identify “all” dependencies. If you can identify a “few” dependencies that would be good enough.

Remember, that the Project Manager of the project would read this SOW to create his project plan, so the more detailed it is, the higher the chances that the Project Manager will be able to create a good project plan, leading to a greater chance of project success.

**Comment by caodaion** [comment]
https://docs.google.com/document/d/1EpiynKFzs8o3MR1EDmFOCPnFy7SJd5E3zrUmYeQ_RHc/edit?usp=sharing
