### ISSUE TITLE
DOCUMENTATION | PROJECT DOCUMENTATION | Project Charter

### ISSUE THREAD

**Issue by nhanntcaodaion** [caodaion/caodaion.github.io#42]
When a project starts, this is the first important document that should be created. If there is an SOW and you are a Project Manager, then one of your first job is to read the SOW thoroughly and prepare a detailed project charter.

Like a SOW, while starting a project many things in the project may not be clear, and that is normal, but try to detail out your thoughts in the project charter with what you know, and check back with the customer, your team and stakeholders regarding points that need to be clarified before you start the actual work.

Remember, that a well written project charter will also make it easier for anybody joining your project to be an effective contributor, because they can refer to the project charter where they can find all the key information about the project. And should you ever hand over the project to somebody else, the handover will be a lot easier for you.

Most companies that I have worked with have a well-defined template/structure for a project charter, but in case your company does not, then you can refer to the following to build up your own project charter.

Typical contents of a good project charter:

- Project overview
- Project Stakeholders
- Scope
- Project schedule
- Budget incl. estimates
- Assumptions
- Responsibilities
- Client responsibilities
- Vendor responsibilities
- Project methodology/phases
- Project Metrics that you plan to collect and the point in time at which you plan to report the metrics.
- Major risks — see below section about the Risk Log
- Change management process — defines how change requests are handled
- Project Governance mechanism including audits
- Communication
- Communication plan – who communicates to whom
- Status Reporting – frequency, templates
- Escalation path
- Any deviation/customizations that you have made from the organization’s standard project process if any

**Comment by caodaion** [comment]
No need this document, 
Please review Project SOW #41
