### ISSUE TITLE
DOCUMENTATION | PROJECT DOCUMENTATION | Project Estimates

### ISSUE THREAD

**Issue by nhanntcaodaion** [caodaion/caodaion.github.io#44]
This is one of the key project documents that I have seen mostly missing in a badly managed project. In most organizations, the project estimation is done by the sales/pre-sales team during the pre-project phase and then this is forgotten. But that should not be the case.

A project as mentioned above may go through various changes.  Therefore it is absolutely necessary that you as the Project Manager make a re-estimation of the project effort and change the project schedule every time there is a change request in the project. Whether the customer will pay for the changes or not is a different question and is entirely commercial, but the fact is a change will impact your project estimates (your manpower requirement) and your project schedule.

At the end of the project, when someone challenges you on the ‘delays” in the project, you, the Project Manager, would be able to defend your stance only if you have maintained your change request history/log, you have re-estimated your project effort and have made changes to the project time schedule and have stored all the previous versions, along with all necessary communications.

The best way to maintain a project estimate is to maintain the project estimate in a different file (such as your budget tracker) and link the latest version to the project charter.
_I record effort estimates in my budgeting sheet, side by side with the actual (or real) effort, which allows me to spot problems early on:_

![Image](https://user-images.githubusercontent.com/118254002/218001068-2b942663-4e5c-4c5e-8a5a-8924cd025096.png)

Labor effort view

I can offer you different types of [budgeting sheets](https://www.tacticalprojectmanager.com/templates/project-budget-template/) which include effort tracking. The months-based budgeting sheet (image above) is included in my [Project Template Pack](https://www.tacticalprojectmanager.com/project-templates-pack/).

**Comment by caodaion** [comment]
No need this document, 
Please review Project SOW #41
