### ISSUE TITLE
DOCUMENTATION | PROJECT DOCUMENTATION | Project Schedule

### ISSUE THREAD

**Issue by nhanntcaodaion** [caodaion/caodaion.github.io#45]
One of the key project documents that you should create and maintain is the project schedule/time-plan.

A good project plan gives you a visual of when the project can end, can show you changes to the schedule as and when you make updates.

Project Schedule Template for Excel

![Image](https://user-images.githubusercontent.com/118254002/218001585-8d1ff7cd-5fe0-43cb-bb15-6600f256f471.png)

_I like to create my project schedules in Excel – you can get this template as part of my [Project Template Pack](https://www.tacticalprojectmanager.com/project-templates-pack/)_

You should also maintain versions of the project schedule, especially if the project is undergoing changes, so that at any point if you are asked why there has been a delay – then you can answer this question.

The best way to maintain a project schedule is to maintain it in a different file and link the latest version to the project plan – remember that a project plan is the master document of your project.

**Comment by caodaion** [comment]
Because this project is a long-term project, So we need to schedule each feature stage.
Use Gantt Chart to tracking the schedule
