### ISSUE TITLE
DOCUMENTATION | PROJECT DOCUMENTATION | Risk Log

### ISSUE THREAD

**Issue by nhanntcaodaion** [caodaion/caodaion.github.io#46]
A risk log is again a key document that you should create and maintain during the project lifecycle.

A Risk Log is basically an Excel sheet with the following columns:

- Description of the risk
- Probability – High, Medium, low
- Impact – High, Medium, low
- Your mitigation/contingency plan

Most organizations that I have seen have a well-defined risk log template (also called risk register). However, if you don’t have a risk log template available, such a template is included in my [Project Template Pack](https://www.tacticalprojectmanager.com/project-templates-pack/) (along with other must-have templates).

This is what my risk log looks like:

![Image](https://user-images.githubusercontent.com/118254002/218001756-9319a8f6-9a4a-4f40-9a19-b8b2cf6183e2.png)

You should also maintain versions of the risk register. Many times, people ask me how often I should update my risk register and there is no defined and set answer to this. In some projects that I have managed I have updated my risk register on a weekly basis and in some projects, I have updated on a fortnightly basis – but one thing for sure is the fact that in all the projects that I have managed, the frequency of updating has never been monthly.

The best way to maintain a risk log is to maintain it in a different file and link the latest version to the project charter – or a project plan as the master document of your project.

**Comment by caodaion** [comment]
No Need this document
