### ISSUE TITLE
DOCUMENTATION | PROJECT DOCUMENTATION | Issue Log

### ISSUE THREAD

**Issue by nhanntcaodaion** [caodaion/caodaion.github.io#47]
Several times I have faced a question on what the difference between a project risk and a project issue is.

A project risk is something that you perceive may happen or may not happen e.g., attrition of a key project team member and you make a plan if the incident happens or does not happen.

A project issue is different, these are items that are hampering your project progress today – example you have not received the project’s database login id and password.

A good project manager usually updates his/her issue log on a daily/weekly basis and discusses the same with the customer/vendor on a daily/weekly basis, as the case may be.

You should also maintain versions of the issue log.

The best way to maintain an issue register is to maintain it in a different file (for example in a RAID Log, which is intended for tracking issues) and link the latest version to the project plan – remember that a project plan is the master document of your project.

![Image](https://user-images.githubusercontent.com/118254002/218001890-e05048b7-1a35-4ac7-b799-4010637f7382.png)

> You don’t necessarily need to create a dedicated Issue Log — you can just record issues in a RAID Log, whose purpose is to capture current issues.

**Comment by caodaion** [comment]
Will include in the requirements documents
