### ISSUE TITLE
DOCUMENTATION | PROJECT DOCUMENTATION | Status Report

### ISSUE THREAD

**Issue by nhanntcaodaion** [caodaion/caodaion.github.io#48]
A well-managed project always has a status report (in a properly defined template) sent out to the customer. Many project managers have told me that they do not send out a project status report because more or less everyday there is a discussion and his/her customer never asks for one.

This I would call a bad practice, irrespective of whether the customer asks for a status report or not, irrespective of the fact if you are having discussions with the customer on a daily basis, as a project manager it is your duty to provide your customer a status report – I would suggest that you send out a status report on a weekly basis.

Trust me – It has been my experience that nothing delights the customer more than a good status report on early Monday morning in his/her mailbox.

You should provide the following in a customer’s status report:

Brief summary of the project progress
Items completed last week
Items planned to be taken up next week
Snapshot of the project schedule/milestones – with upcoming milestones highlighted
Updated Project risks and their mitigation
Current project issues and their status
It takes years of experience and practice to design a good status report template that fits the requirement/project/the customer, but you can take the above points as a start.

One more point, you would have to remember is that not all projects will run smoothly, and if at a particular point in time a project turns bad, then if you have sent out a project status report that acts as documented evidence that the issues in the project have been highlighted to the customer.

**Comment by caodaion** [comment]
View project Gantt Chart
