### ISSUE TITLE
DOCUMENTATION | PROJECT DOCUMENTATION | Test Cases/Plan

### ISSUE THREAD

**Issue by nhanntcaodaion** [caodaion/caodaion.github.io#49]
It is mandatory to draw up test cases/ plans for your project, especially if it is a development project. Test cases can be at multiple levels:

Unit test case – drawn up at program level
Integration test case – to test integrations with other systems, APIs etc.
System test cases – to test the system as a black box
If you, as a project manager, have to ensure the quality of your software project, trust me, you cannot miss out on test cases. Most team members do not want to detail out test case and this is where you have to enforce as a project manager.

Without detailed test cases, no one can ensure the quality of the output irrespective of how good the team is in programming – it is human nature to miss out on a feature or that extra “IF clause” or that “obvious validation”.

If you are creating a test case template yourself, then you should ensure that it contains the following:

Test case number – a unique number that identifies this test case.
Feature
Pre-conditions to this test scenario
Post conditions to this test scenario
Test scenario
Expected Result
Actual Result – you can use the test case template to log the actual result on running the test – in this case it becomes a test case and a test log.
Pass/Fail – you can use the test case template to log the actual result on running the test – in this case it becomes a test case and a test log.
Below you can see the template I use for test cases. Have used it a million times in ERP system implementations, but you can use it for basically any IT project:

![Image](https://user-images.githubusercontent.com/118254002/218002082-cca1cccc-ae09-4830-b6f3-6e8e47ab7fda.png)

**Comment by caodaion** [comment]
Includes in the project requirements
