### ISSUE TITLE
DOCUMENTATION | PROJECT DOCUMENTATION | Requirement specification

### ISSUE THREAD

**Issue by nhanntcaodaion** [caodaion/caodaion.github.io#50]
If you are leading a software development or system implementation project – such as an ERP rollout, then this is a must have document that is required to be prepared.

A requirement specification is a detailed document that serves as a guide to the development team on the various features that need to be present in the system. Usually, a requirement specification follows a modular approach which means that you identify various modules (or processes) and then drill down/detail out the requirements at a detailed level.

To describe each feature, a diagrammatic approach along with a detailed logic of the feature is usually the best way to go about. Examples of diagrams that may be included are:

Context diagram: A bird’s eye level view of the module/feature showing the various users that interact with the system
Process flow diagram: usually a flow chart or swim lane diagram defining the proces
When you have had a business analyst prepare the above, what you have is the functional requirement – meaning the various features/functionality to be present in the system. However, it has been my experience that many times, people forget to write out non-functional requirements.

A non functional requirement is, in short, a system requirement but it cannot be directly connected with any module/feature/functionality. Example of non-functional requirements are:

- Number of concurrent users, of the system
- Any particular performance criteria that is present e.g. a transaction should be approved/rejected in 20 seconds

The next phase of the project after analysis is the design (or implementation) phase and in order to do a good design, non-functional requirements come in handy. The point that you have to remember is that if you have not catered to the non-functional requirements, then even if during the final user acceptance testing, it is seen that you have catered to all the functional requirements, even then your project will not get passed.

In short, non-functional requirements are usually a very small part of the requirement, but they are perhaps the most neglected/least documented, and as a good project manager it is your job to document the non-functional requirements and see to it that the system design caters to these. (Check out this page from California Polytechnic State University for an [overview of non-functional requirements](http://users.csc.calpoly.edu/~jdalbey/SWE/QA/nonfunctional.html)).

If you are looking for a Requirement Specification template, check out [my requirement specification template](https://www.tacticalprojectmanager.com/requirement-specification-template-requirement-numbering/) which supports automatic numbering of requirements and matching of customer & product requirements (to ensure traceability).

**Comment by caodaion** [comment]
Each requirement for each feature or screen must write in the GitHub issue description.
