### ISSUE TITLE
UAT | Research on how to improve the notification function

### ISSUE THREAD

**Issue by caodaion** [caodaion/caodaion.github.io#51]
We need to improve the notification functionto allow push notification from the server that the user no need to open the PWA on

**Comment by nhanntcaodaion** [comment]
The best solution is push notification from the server site.
But with the current hosting (firebase hosting), we cannot implement this function
Must a server run node.js that allows running the `npm start` command in the **package.json** file

**Comment by nhanntcaodaion** [comment]
Because the current hosting (Firebase) does not support server sites like Heroku, so we need to research to set HTTPS for Heroku with the custom domain

**Comment by nhanntcaodaion** [comment]
https://github.com/caodaion/caodaion.github.io/issues/51#issuecomment-1451819393
Based on this comment, I just try to set HTTPS for the custom domain but not work. Just reverted to the firebase hosting

**Comment by nhanntcaodaion** [comment]
At this moment, just use Heroku can localhost to test for the notification function.
All the other items will be deployed on firebase hosting until the server site has been bought
