### ISSUE TITLE
Development environment installation

### ISSUE THREAD

**Issue by nhanntcaodaion** [caodaion/caodaion.github.io#98]
# Requirement:
- [x] Install Visual Studio Code.
    - [x] Install Live Server extension of VSCode.

- [x] Install Slack to communication

# Report:
- After completing the installation, take the screenshot for each item.
- Tick on the check to confirm the item has been completed.

**Comment by hiepntcaodaion** [comment]
![Image](https://github.com/caodaion/caodaion.github.io/assets/143392222/bc8b42c0-51d7-4c56-b625-28102c5ada90)



![Image](https://github.com/caodaion/caodaion.github.io/assets/143392222/aee7779d-ac97-4fea-be18-7a359995b6e9)



![Image](https://github.com/caodaion/caodaion.github.io/assets/143392222/463ab05c-9776-45a4-860f-459a1ccda37b)
